events/urls.py
from django.conf.urls import patterns, include, url
from events import views


urlpatterns = patterns('',

    url(r'^tonight/$', views.tonight, name='ev_tonight'),
    url(r'^create/$', views.create, name='ev_create'),
    url(r'^toggle-attendance/$', views.toggle_attendance,
    	name="ev_toggle_attendance"),
    url(r'^archive/$', views.archive, name='ev_archive'),
)

socialgraph/urls.py
from django.conf.urls import patterns, include, url
from socialgraph import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'startthedark.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(
    	r'^followers/(?P<username>[a-zA-Z0-9_-]+)/$',
    	views.friend_list,
    	{'list_type': 'followers'},
    	name='sg_followers'
    	),

    url(
    	r'^following/(?P<username>[a-zA-Z0-9_-]+)/$',
    	views.friend_list,
    	{'list_type': 'following'},
    	name='sg_followers'
    	),

    url(
    	r'^mutual/(?P<username>[a-zA-Z0-9_-]+)/$',
        views.friend_list,
    	{'list_type': 'mutual'},
    	name='sg_followers'
    	),
)

startthedark/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'startthedark.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^events/', 	include('events.urls', namespace='events')),
    url(r'^admin/', 	include(admin.site.urls)),
    url(r'^friends/', 	include('socialgraph.urls', namespace='sg')),

    )

events/models.py
from datetime import datetime, timedelta

from django.db import models
from django.db.models.query import QuerySet
from django.contrib.auth.models import User

def today():
	now = datetime.now()
	#start of the day
	start = datetime.min.replace(year= now.year, month=now.month, day=now.day)
	#end of the day
	end = (start + timedelta(days=1)) - timedelta.resolution
	return (start, end)


class EventQuerySet(QuerySet):
	
	def today(self):
		return self.filter(creation_date__range=today())


class EventManager(models.Manager):
	
	def get_queryset(self):
		return EventQuerySet(self.model)

	def today(self):
		return self.get_query_set().filter(creation_date__range=today())


class Event(models.Model):
	creation_date = models.DateTimeField(default=datetime.now)
	start_date = models.DateTimeField(null=True, blank=True)
	description = models.TextField()
	creator = models.ForeignKey(User, related_name='event_creator_set')
	attendees = models.ManyToManyField(User, through='Attendance')
	latest = models.BooleanField(default=True)

	objects = EventManager()

	def __unicode__(self):
		return self.description

	def save(self, **kwargs):
		Event.objects.filter(latest=True, creator=self.creator).today().update(latest=False)
		super(Event, self).save(**kwargs)


class Attendance(models.Model):
	user = models.ForeignKey(User)
	event = models.ForeignKey(Event)
	registration_date = models.DateTimeField(default=datetime.now)

	def __unicode__(self):
		return "{0} is attending {1}".format(self.user.username, self.event)

	class Meta:
		verbose_name_plural = 'attendance'

socialgraph/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User



class UserLink(models.Model):
	from_user = models.ForeignKey(User, related_name='following_set')
	to_user = models.ForeignKey(User, related_name='follower_set')
	date_added = models.DateTimeField(default=datetime.now)

	def __unicode__(self):
		return "{0} is following {1}".format(self.from_user.username,
			self.to_user.username)

	def save(self, **kwargs):
		if self.from_user == self.to_user:
			raise ValueError('Cannot follow yourself.')
		super(UserLink, self).save(**kwargs)

	class Meta(object):
		unique_together = (('to_user', 'from_user'),)

events/forms.py
from django import forms
from .models import Event

class EventForm(forms.ModelForm):
	
	description = forms.CharField(max_length=340, widget=forms.Textarea)
	
	class Meta:
		model = Event
		fields = ('description', )

events/views.py
from django.shortcuts import render, get_object_or_404
from dateutil.parser import parse
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Event, Attendance
from .forms import EventForm


def tonight(request):
	events = Event.objects.today().filter(latest=True)
	context = {
	'events': events,

	}
	return render(request, 'events/tonight.html', context)

@login_required
def create(request):
	form = EventForm(request.POST or None)
	if form.is_valid():
		event = form.save(commit=False)
		event.creator = request.user #Who is logged in?

		#Guess the date from the text
		guessed_date = None
		for word in event.description.split():
			try:
				guessed_date = parse(word)
				break
			except ValueError:
				continue

		event.start_date = guessed_date
		event.save()

		messages.success(request, "Your event was posted")

		if 'next' in request.POST:
			next = request.POST['next']
		else:
			next = reverse('events:ev_tonight')
		return HttpResponseRedirect(next)

	return render(request, 'events/create.html', {'form': form})

@login_required
def toggle_attendance(request):
	try:
		event_id = int(request.POST['event_id'])
	except (KeyError, ValueError):
		raise Http404

	event = get_object_or_404(Event, id=event_id)
	attendance, created = Attendance.objects.get_or_create(user=request.user,
		event=event)
	if created:
		messages.success(request, "Your are now attending {0}".format(event))
	else:
		attendance.delete()
		messages.success(request, "You are no longer attending {0}".format(event))

	next = request.POST.get('next', '')

	if not next:
		next = reverse('events:ev_tonight')

	return HttpResponseRedirect(next)



def archive(request):
	events = Event.objects.filter(latest=True)
	context = {
	'events': events
	}
	return render(request, 'events/tonight.html', context)

socialgraph/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.models import User

from .models import UserLink
from .util import get_people_user_follows, get_people_following_user
from .util import get_mutual_followers

FRIEND_FUNCTION_MAP = {
	'followers': get_people_user_follows,
	'following': get_people_following_user,
	'mutual': get_mutual_followers,
}

def friend_list(request, list_type, username):
	user = get_object_or_404(User, username=username)
	context = {
	'list_type': list_type,
	'friends': FRIEND_FUNCTION_MAP[list_type](user),
	}

	return render(request, 'socialgraph/friend_list.html', context)

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}StartTheDark{% endblock %}</title>
	{% block extra_head %}{% endblock %}
</head>
<body>
	<ul>
		<li>
			<a href="{% url 'events:ev_tonight' %}">Tonight</a>
		</li>
		<li>
			<a href="{% url 'events:ev_archive' %}">Archive</a>
		</li>
	</ul>
	{% block main_content %}{% endblock %}
	{% block extra_body %}{% endblock %}
</body>
</html>

templates/events/archive.html
{% extends "base.html" %}
{% load events_tags %}

{% block title %}Archive - {{ block.super }}{% endblock %}


{% block main_content %}
	<a href="{% url 'events:ev_create' %}">Create an Event</a>
	{% if events %}
		{% for e in events %}
			{% event e %}

		{% endfor %}

	{% else %}
		<p>No events for today</p>

	{% endif %}

{% endblock %}

templates/events/create.html
{% extends "base.html" %}

{% block title %}Create - {{ block.super }} {% endblock %}

{% block main_content %}
<form method="post" action="">
	{% csrf_token %}
	<ul>
	{{ form.as_ul }}
	</ul>

	<input type="submit" value="Create Event">

</form>

{% endblock %}

templates/events/event.html
<p>{{ event.creator.username }}: {{ event.description }}</p>
{% if attending %}
	<p>You are attending this event</p>
{% else %}
	<p>You are not attending this event</p>
{% endif %}

<form method="post" class="toggle_attendance_form" action="{% url 'events:ev_toggle_attendance'%}">
	{% csrf_token %}
	<input type="hidden" name="event_id" value="{{ event.id }}">
	{% if attending %}
	<input class="attendance unattend" type="submit" value="Unattend">
	{% else %}
	<input class="attendance attend" type="submit" value="Attend">
	{% endif %}
</form>

templates/events/tonight.html
{% extends "base.html" %}
{% load events_tags %}
{% block title %}Tonight - {{ block.super }}{% endblock %}


{% block main_content %}
	<a href="{% url 'events:ev_create' %}">Create an Event</a>
	{% if events %}
		{% for e in events %}
			{% event e %}

		{% endfor %}

	{% else %}
		<p>No events for today</p>

	{% endif %}

{% endblock %}

templates/socialgraph/friend_list.html
{% extends "base.html" %}

{% block title %}Friend list - {{ block.super }}{% endblock %}


{% block main_content %}

	{% ifequal list_type "followers" %}

		<h1>People Who You Follow</h1>

	{% else %}

		{% ifequal list_type "following" %}

			<h1>People Following You</h1>

		{% else %}
			<h1>People Who You Follow And Also Follow You</h1>

		{% endifequal %}

	{% endifequal %}

	{% ifequal friends.count 0 %}
		<p class="info">You Don't Have Any</p>
	{% else %}
		<ul>
			{% for friend in friends %}
				<li>{{ friend.username }}</li>
			{% endfor %}
		</ul>

	{% endifequal %}

{% endblock %}